CREATE TABLE IF NOT EXISTS WORDS (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  japanese TEXT NOT NULL,
  romaji TEXT NOT NULL,
  english TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS GROUPS (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS WORDS_GROUPS (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  word_id INTEGER NOT NULL,
  group_id INTEGER NOT NULL,
  FOREIGN KEY (word_id) REFERENCES WORDS(id),
  FOREIGN KEY (group_id) REFERENCES GROUPS(id)
); 